-- Global exact-question retrieval cache.
-- Stores only retrieved legal context/sources. Final answers are always
-- regenerated by the LLM from this cached context.

CREATE TABLE IF NOT EXISTS retrieval_cache (
  cache_key TEXT PRIMARY KEY,
  normalized_question TEXT NOT NULL,
  intent TEXT NOT NULL,
  context_chunks JSONB NOT NULL DEFAULT '[]'::jsonb,
  sources JSONB NOT NULL DEFAULT '[]'::jsonb,
  related_laws JSONB NOT NULL DEFAULT '[]'::jsonb,
  related_cases JSONB NOT NULL DEFAULT '[]'::jsonb,
  sources_used INTEGER NOT NULL DEFAULT 0,
  retrieval_quality JSONB NOT NULL DEFAULT '{}'::jsonb,
  retrieval_timing JSONB NOT NULL DEFAULT '{}'::jsonb,
  cache_version TEXT NOT NULL,
  retrieval_speed_mode TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  hit_count INTEGER NOT NULL DEFAULT 0,
  last_hit_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS retrieval_cache_expires_intent_idx
  ON retrieval_cache (expires_at, intent);

CREATE INDEX IF NOT EXISTS retrieval_cache_normalized_question_idx
  ON retrieval_cache (normalized_question);

CREATE INDEX IF NOT EXISTS retrieval_cache_question_version_expires_idx
  ON retrieval_cache (normalized_question, cache_version, expires_at DESC);

CREATE INDEX IF NOT EXISTS retrieval_cache_version_mode_idx
  ON retrieval_cache (cache_version, retrieval_speed_mode);
